### PR TITLE
:lipstick:Add download quantity statistics for the latest release.

### PR DESCRIPTION
**Pull request by aiguoli**
Add download quantity statistics for the latest release.

### CODE REVIEW

**Review by OKEAMAH — APPROVED** [review]
Cool

**Review by OKEAMAH — APPROVED** [review]
Cool

**Review by OKEAMAH — APPROVED** [review]
Cool

**Comment by wei** [comment]
Thanks for the contribution! At this time we have decided to not add this feature due to low usage but we may add it in the future should there be more need. 

If you'd like, we do have a few [help needed issues](https://github.com/wei/socialify/issues?q=is:issue+is:open+label:%22help+wanted%22) we'd love to incorporate into Socialify. Just comment on the ones you're interested in and we'd love your contribution!

Many thanks!

**Pull request closed without merging**
