### PR TITLE
⬆️ Upgraded yarn from class to berry (required for next15 migration)

### PR DESCRIPTION
**Pull request by KemingHe**
Upgraded yarn from classic (no config) to the modern yarn berry version with newly auto-generated base config files such as `.yarn/` and `.yarnrc.yml` (added disable telemetry.)

Rationale is that, according to the official Next15 migration guide, the best way is to run `npx @next/codemod@canary upgrade latest`. Half-way through the process, it has a step calling `yarn dlx ...` and the `dlx` command is only available to yarn berry.

_Another HUGE benefit of this pre-req update is that now we specify which exact yarn version Socialify is using in `package.json`_ This further limits unexpected dev behaviors for future commits.

Ref https://github.com/KemingHe/contrib-socialify/blob/6dcf2f21c8aeb9090f526c9a82fed5ffd0d401dc/package.json#L86C3-L86C169

```JSON
"packageManager": "yarn@4.5.3+sha512.3003a14012e2987072d244c720506549c1aab73ee728208f1b2580a9fd67b92d61ba6b08fe93f6dce68fd771e3af1e59a0afa28dd242dd0940d73b95fedd4e90"
```

<hr />

Alternative is to do the upgrade manually and keep yarn out of date.

### CODE REVIEW

**Comment by KemingHe** [comment]
The build is failing due to outdated Action scripts, before I go that fix that, @wei what are your thoughts?

**Comment by wei** [comment]
@KemingHe I'm leaning towards not including this for the moment as I plan to switch to `pnpm` instead in the near future which also has first class support from `actions/setup-node`.

**Comment by KemingHe** [comment]
> @KemingHe I'm leaning towards not making this change for the moment as I plan to switch to `pnpm` in the near future which also has first class support from `actions/setup-node`.

I'm actually really happy to hear that as I've been using `pnpm` for a long time and switching to yarn _only_ for Socialify is, well, less convenient. 

Shall we make the switch to `pnpm` now then?

**Comment by wei** [comment]
> I'm actually really happy to hear that 

Haha, not a bad idea to get that out of the way first before Next.js 15.

**Comment by KemingHe** [comment]
Shall I create a similar PR but migrating to `pnpm` instead? I will close this one on approval.

**Comment by wei** [comment]
Yes, approved. ❤️

**Pull request closed without merging**
