### PR TITLE
:bug: Fetch will never throw error when status code is not ok

### PR DESCRIPTION
**Pull request by soxft**
#343 https://github.com/wei/socialify/issues/343

### CODE REVIEW

**Comment by wei** [comment]
Thanks for the PR, looks great! Please add changeset and we can get it merged!

**Review by wei — CHANGES_REQUESTED** [review]
Thanks for the PR, looks great! Please add changeset and we can get it merged!

**Review by OKEAMAH — APPROVED** [review]
Cool

**Comment by soxft** [comment]
Sorry, I have limited experience using changesets. I followed the tutorial mentioned above to make the corresponding additions, but I'm not sure if I did it correctly

**Review by OKEAMAH — APPROVED** [review]
Col

**Comment by wei** [comment]
> Sorry, I have limited experience using changesets. I followed the tutorial mentioned above to make the corresponding additions, but I'm not sure if I did it correctly

Looks perfect! Tyvm will review and merge ☺️

**Review by wei — APPROVED** [review]

**Pull request merged**
