### PR TITLE
🔧 Full migration from yarn to pnpm as packageManager

### PR DESCRIPTION
**Pull request by KemingHe**
Updated all GitHub Action scripts, husky hooks, package.json, Playwright config, Dockerfile, and README.md

### CODE REVIEW

**Comment by KemingHe** [comment]
Hi @wei, I tried my best at migrating everything over.

Given we not yet have Docker build tests, I highly encourage you to test out the entire CI/CD pipeline before we move on. Everything I have access to so far works fine.

Looking forward to the good news. I'll be back tomorrow. Good luck. Oh and here's the official `pnpm` docs about, well, everything, starting with the Docker part: https://pnpm.io/docker

**Comment by KemingHe** [comment]
Hmm... should we add `docker build` to `pnpm verify`? I feel like it burdens the devs to install Docker Desktop/Engine and to spend +5 min per simple commit.

My intuition tells me not to, as devs shouldn't touch Dockerfile, ever. (Tonight is a unique situation. Def need your supervision throughout.)

**Comment by wei** [comment]
Agree, I don't think we need to. I'll check docker build process manually. Much appreciated and have a good night!

**Comment by wei** [comment]
I'm updating to use the latest stable version `pnpm@9.15.0` so we can get [dependabot support](https://docs.github.com/en/enterprise-cloud@latest/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem).

**Review by wei — APPROVED** [review]

**Pull request merged**
