### PR TITLE
💚 Require GITHUB_TOKEN in CI

### LINKED ISSUE #422: Test(enhancement): for e2e tests, use `dotenv` or automated scripts to set GITHUB_TOKEN instead of manually asking from devs every session
## Problem

`playwright.config.ts` now asks for GITHUB_TOKEN per dev session. This is inconvenient and the workaround is dangerous as devs will export their GitHub token at the beginning of every session.

```Typescript
// CI-friendly but not developer-friendly.
// TODO: Recommend using dotenv instead, plus, "next build && next start"
// already sets the environment variable if .env is present.
if (!process.env.GITHUB_TOKEN) {
  console.error('Please set GITHUB_TOKEN before running the tests')
  process.exit(1)
}
```

## Proposed Solution

Instead of in `playwright.config.ts`, we can add a check for `process.env.GITHUB_TOKEN` in the nextjs app, since that `next build && next start` already loads the .env if present.

### PR DESCRIPTION
**Pull request by KemingHe**
Very simple and effective fix that stays within the CI boundaries, not affecting application:

Ref https://github.com/KemingHe/contrib-socialify/blob/d6e32fa50be0ef1702c2889d0a2a5ff32cb09671/playwright.config.ts

```Typescript
// Insta-fail the test run in CI if GITHUB_TOKEN is not set.
// This is because `next start` auto-loads dev-side .env files,
// which are not present in GitHub Action CI run.
if (process.env.CI && !process.env.GITHUB_TOKEN) {
  console.error('Please set GITHUB_TOKEN before running the tests')
  process.exit(1)
}
```

Also fixed typo in comments introduced when resolving #423 .

Solution to fix #422 . Edit: more context.

### CODE REVIEW

**Comment by KemingHe** [comment]
> Should we remove the check from playwright.config.ts and move to next app?

I propose we do both, and I have some addition context (updating comment...

**Comment by KemingHe** [comment]
...continued 

- The current frontend is perfectly decoupled from the backend, and GITHUB_TOKEN is only relevant server-side (I'm actually proposing to add the `server-only` package to enforce this setup).
- We shouldn't crash the frontend if backend is missing an env. Thus we should instead rely on backend response erroring in the Playwright user story to catch the token issue, and not block the frontend.

**Comment by KemingHe** [comment]
There is a third option, but that's for `Jest/Vitest` and not for Playwright: 

https://github.com/KemingHe/buckeye-gpt/blob/871971f97972bc902f1e22f069d870093cbe9e6c/src/constants/openAIConstants.test.ts

**Comment by wei** [comment]
TY for the thorough explanation. I'm not looking to check the validity of the token, I'm merely talking about checking the existence of the token in environment variable. 

You raise a good point. We still want to allow building without needing the `GITHUB_TOKEN` as the token is only required during runtime. We could write a check inside a [custom server](https://nextjs.org/docs/pages/building-your-application/configuring/custom-server) but that maybe overkill for now. Let's merge the current solution for now~

**Review by wei — APPROVED** [review]

**Comment by KemingHe** [comment]
Hi @wei, the `next.config.js` you just edited will cause an issue once we upgrade to Next15. I put it there as a pre-measure.

**Comment by KemingHe** [comment]
Next15 auto-displays a next server icon that overlays the render frontend, and it's not consistent per render as it has its own hydration timing.

**Comment by KemingHe** [comment]
Oh wait, we are using prod server for `Playwright`, maybe this won't matter?

**Comment by wei** [comment]
We don't use the development server anymore for e2e. `next start` will not include this icon.

**Pull request merged**
