### PR TITLE
👷 Replace eslint with biomejs

### LINKED ISSUE #271: Upgrade to ESLint 9.x
Let's clean up the extraneous eslint plugins and configs we have. The simpler, the better ➖

### LINKED ISSUE #272: Upgrade to Next.js 14 Best Practices
In addition to just bumping the version like in https://github.com/wei/socialify/pull/268, let's also update the [project structure](https://nextjs.org/docs/getting-started/project-structure) to the latest recommended by Next.js (App directory). Let's also explore the use of server components (if applicable).

### PR DESCRIPTION
**Pull request by KemingHe**
Resolved #271 through successful, fully secured biomejs migration.

### CODE REVIEW

**Comment by KemingHe** [comment]
I finally learned to keep contribs lean, about time. 😅

**Comment by KemingHe** [comment]
@wei By the way, is there anything I should do after running `npx changeset`? I see that it always creates a tmp file.md and it takes effort for you to remove it each time. Just want to ask. 🤔

**Comment by wei** [comment]
Awesome 🙌 . Could you create a branch for each task instead of using your master branch for all the changes?



> @wei By the way, is there anything I should do after running `npx changeset`? I see that it always creates a tmp file.md and it takes effort for you to remove it each time. Just want to ask. 🤔

No, that's all. This is how changeset app works, after merging changeset will create a PR to update our changelog, bump release versions.

**Review by wei — CHANGES_REQUESTED** [review]
Awesome 🙌 . Could you create a branch and PR for each task instead of using your master branch for multiple changes?

**Comment by wei** [comment]
As a first step of #272, we can merge in https://github.com/wei/socialify/pull/289 so you can just update this PR to include only biome changes.

**Comment by wei** [comment]
I will make the aforementioned updates.

**Review by wei — APPROVED** [review]
LGTM!

**Comment by wei** [comment]
@KemingHe thanks very much for your contribution!! Merging for now. 🚀 

For the future, I recommend creating a separate branch for each task/PR instead of working on master branch~ 😄

**Comment by KemingHe** [comment]
> @KemingHe thanks very much for your contribution!! Merging for now. 🚀
> 
> For the future, I recommend creating a separate branch for each task/PR instead of working on master branch~ 😄

Understood, will do from now on.

**Pull request merged**
